name: Check Coupon Every 10 Mins
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Cập nhật lên v4
      - name: Setup Python
        uses: actions/setup-python@v5 # Cập nhật lên v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Run bot
        run: python check.py
