- name: Run bot
        run: python check.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add last_code.txt
          git commit -m "Update last code cache" || exit 0
          git push
